### DISCUSSION TITLE
How are private keys stored and in what format?

### DISCUSSION THREAD

**Discussion by hangindev** [walt-id/.github#11] [Help] [answered]
Hi, I am studying the implementation of Wallet Kit. Am I corrent that the keys can be stored in the backend by the wallet provider, with different key store implementations, incl `SqkKeyStoreService`, `HKVKeyStoreService`, etc? The key is and encoded as base64 but not in any form encrypted right?

**Comment by waltkb** [comment, marked as answer]
By setting
```
id.walt.services.keystore.KeyStoreService=id.walt.services.keystore.EncryptedKeyStore:crypto.conf
```
in the `service-matrix.properties`, you can utilize the EncryptedKeyStore.

Here is an example `crypto.conf` to use:
```yml
encryption-at-rest-key: "CHANGE-ME" # your secret key
key-format: PEM                     # [PEM / BASE64_DER / BASE64_RAW]
keys-root: keys                     # default: "keys"
alias-root: alias                   # default: "alias"
```
