### DISCUSSION TITLE
Using verifier api from issuer portal

### DISCUSSION THREAD

**Discussion by srivatsavchenna** [walt-id/.github#37] [Help]
Hello, how do I call verifier apis (verifier running on 8000 port) from the issuer portal (issuer running on 8002 port) , currently I get a CROS error. Is there some configuration files that I have to change?

**Comment by waltkb** [comment]
We are mostly using URL rewriting for these instances; e.g. example for Kubernetes:

```yaml
    - host: verifier.walt-test.cloud
      http:
        paths:
          - path: /verifier-api/
            pathType: Prefix
            backend:
              service:
                name: walletkit
                port:
                  number: 80
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: walletkit
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: verifier-portal
                port:
                  number: 80
    - host: issuer.walt-test.cloud
      http:
        paths:
          - path: /issuer-api/
            pathType: Prefix
            backend:
              service:
                name: walletkit
                port:
                  number: 80
          - path: /onboarding-api/
            pathType: Prefix
            backend:
              service:
                name: walletkit
                port:
                  number: 80
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: walletkit
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: issuer-portal
                port:
                  number: 80
```
